Repository MicrosoftDocs/OfficeDocs-SharePoint-PowerShell, pull requests merged in 2022-06, with the labels that each got.

#263 resolve xref-not-found
  sharepoint/sharepoint-ps/sharepoint-server/Get-SPODataConnectionSetting.md
Labels: Microsoft submitter

#262 Publish 06/13/2022, 10:30 AM
  sharepoint/sharepoint-ps/sharepoint-server/Get-SPODataConnectionSetting.md
  sharepoint/sharepoint-server-ps/sharepoint-server/Get-SPSite.md
Labels: Admin review, Microsoft submitter

#264 Publish 06/14/2022, 10:30 AM
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOSite.md
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md
Labels: Microsoft submitter

#265 Publish 06/15/2022, 10:30 AM
  sharepoint/sharepoint-ps/sharepoint-online/Connect-SPOService.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOMalwareFile.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOMalwareFileContent.md
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOBuiltInSiteTemplateSettings.md
Labels: Microsoft submitter

#267 Publish 06/16/2022, 10:30 AM
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenantTaxonomyReplicationParameters.md
Labels: Microsoft submitter

#266 Update docfx.json
  sharepoint/docfx.json
Labels: Admin review

#269 Publish 06/17/2022, 10:30 AM
  sharepoint/docfx.json
Labels: Microsoft submitter

#253 Add the yaml file for PowerShell Updatable Help (CabGen) CI
  cabgen-bootstrap.yml
Labels: Microsoft submitter

#271 OOB Publish
  cabgen-bootstrap.yml
Labels: Microsoft submitter
