Repository MicrosoftDocs/OfficeDocs-SharePoint-PowerShell, pull requests merged in 2024-06, with the labels that each got.

#642 Update Set-SPOTenant.md
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md
Labels: Microsoft submitter, Sign off

#643 Update Set-SPOSite.md
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOSite.md
Labels: In review, Microsoft submitter, Sign off

#647 publish main to live 6/3/24 10:30 AM
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOSite.md
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md
Labels: Microsoft submitter

#648 Remove ms.topic, which is defined in docfx.json
  sharepoint/sharepoint-ps/sharepoint-online/Add-SPOListDesign.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOTenantRenameSitePrioritization.md
  sharepoint/sharepoint-ps/sharepoint-online/Remove-SPOTenantRenameSitePrioritization.md
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenantRenameSitePrioritization.md
Labels: In review, Microsoft submitter, Sign off

#649 Publish main to live 06/03/2024, 3:30 PM
  sharepoint/sharepoint-ps/sharepoint-online/Add-SPOListDesign.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOTenantRenameSitePrioritization.md
  sharepoint/sharepoint-ps/sharepoint-online/Remove-SPOTenantRenameSitePrioritization.md
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenantRenameSitePrioritization.md
Labels: Microsoft submitter

#651 updating file extensions to .md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOContainerTypeConfiguration.md
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOApplication.md
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOContainerTypeConfiguration.md
Labels: Microsoft submitter

#652 merge to live
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOContainerTypeConfiguration.md
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOApplication.md
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOContainerTypeConfiguration.md
Labels: Microsoft submitter
