Repository MicrosoftDocs/OfficeDocs-SharePoint-PowerShell, pull requests merged in 2024-12, with the labels that each got.

#768 Add docs for Disabled Adaptive Card Extension Ids
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md
Labels: In review, Microsoft submitter, Sign off

#769 Published main to live, Wednesday 5:00 PM IST, 12/04
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md
Labels: Microsoft submitter

#765 Set-SPOCopilotPromoOptInStatus.md
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOCopilotPromoOptInStatus.md
Labels: In review, Sign off

#770 Published main to live, Wednesday 10:30 AM PST, 12/04
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOCopilotPromoOptInStatus.md
Labels: Microsoft submitter

#771 Correct invisible content (disallowed-html-tag)
  sharepoint/sharepoint-ps/sharepoint-online/Revoke-SPOUserSession.md
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOMigrationPackageAzureSource.md
  sharepoint/sharepoint-ps/sharepoint-online/Unregister-SPOHubSite.md
Labels: In review, Microsoft submitter, Sign off

#772 Publish main to live, 12/04/24, 3:30 PM PT
  sharepoint/sharepoint-ps/sharepoint-online/Revoke-SPOUserSession.md
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOMigrationPackageAzureSource.md
  sharepoint/sharepoint-ps/sharepoint-online/Unregister-SPOHubSite.md
Labels: Microsoft submitter

#757 Create Set-SPORestrictedSiteCreation.md
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPORestrictedSiteCreation.md
  sharepoint/sharepoint-ps/sharepoint-online/sharepoint-online.md
Labels: In review, Microsoft submitter, Sign off

#759 Create Get-SPORestrictedSiteCreation
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPORestrictedSiteCreation.md
  sharepoint/sharepoint-ps/sharepoint-online/sharepoint-online.md
Labels: In review, Microsoft submitter, Sign off

#773 Publish main to live, 12/09/24, 3:30 PM PT
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPORestrictedSiteCreation.md
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPORestrictedSiteCreation.md
  sharepoint/sharepoint-ps/sharepoint-online/sharepoint-online.md
Labels: Microsoft submitter

#776 Update Get-SPOUserAndContentMoveState.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOUserAndContentMoveState.md
Labels: In review, Microsoft submitter, Sign off

#775 Update Get-SPOUnifiedGroupMoveState.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOUnifiedGroupMoveState.md
Labels: In review, Microsoft submitter, Sign off

#777 Publish main to live, 12/12/24, 3:30 PM PT
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOUnifiedGroupMoveState.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOUserAndContentMoveState.md
Labels: Microsoft submitter

#778 Update Set-SPORestrictedSiteCreation.md
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPORestrictedSiteCreation.md
Labels: In review, Microsoft submitter, Sign off

#774 Add documentation for the Copilot Insights Cmdlets
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOCopilotAgentInsightsReport.md
  sharepoint/sharepoint-ps/sharepoint-online/Start-SPOCopilotAgentInsightsReport.md
  sharepoint/sharepoint-ps/sharepoint-online/sharepoint-online.md
Labels: In review, Microsoft submitter, Sign off

#780 Publish main to live, 12/13/24, 3:30 PM PT
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOCopilotAgentInsightsReport.md
  sharepoint/sharepoint-ps/sharepoint-online/Start-SPOCopilotAgentInsightsReport.md
  sharepoint/sharepoint-ps/sharepoint-online/sharepoint-online.md
Labels: Microsoft submitter

#781 Corrected parameter list for this command
  sharepoint/sharepoint-ps/sharepoint-online/Export-SPODataAccessGovernanceInsight.md
Labels: In review, Microsoft submitter, Sign off

#782 Published main to live, Friday 5:00 PM IST, 12/27
  sharepoint/sharepoint-ps/sharepoint-online/Export-SPODataAccessGovernanceInsight.md
Labels: Microsoft submitter
