Repository MicrosoftDocs/OfficeDocs-SharePoint-PowerShell, pull requests merged in 2024-10, with the labels that each got.

#701 Update Set-SPOTenant.md
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md
Labels: In review, Sign off

#702 Publish main to live, Thursday 3:30PM PDT, 10/03
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md
Labels: Microsoft submitter

#705 publish main to live, 10/10/2024, 10:30 AM PT
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOSite.md
Labels: Microsoft submitter

#703 Update Set-SPOTenant.md
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md
Labels: Microsoft submitter

#706 Publish main to live, Tuesday 3:30PM PDT, 10/15
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md
Labels: Microsoft submitter

#707 Update Set-SPTrustedIdentityTokenIssuer.md - Add UseStateToRedirect info
  sharepoint/sharepoint-server-ps/sharepoint-server/Set-SPTrustedIdentityTokenIssuer.md
Labels: In review, Microsoft submitter, Sign off

#708 Publish main to live, Wednesday 3:30PM PDT, 10/16
  sharepoint/sharepoint-server-ps/sharepoint-server/Set-SPTrustedIdentityTokenIssuer.md
Labels: Microsoft submitter

#711 add HidePeoplePresenceInLists to Set-SPOSite
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOSite.md
Labels: In review, Microsoft submitter, Sign off

#710 Remove Preview Tag
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOSite.md
Labels: In review, Microsoft submitter, Sign off

#712 Publish main to live, Wednesday 5:00 PM IST, 10/23
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOSite.md
Labels: Microsoft submitter

#696 Update Set-SPOApplication.md
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOApplication.md
Labels: In review, Sign off

#713 Publish main to live, Wednesday 3:30PM PDT, 10/23
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOApplication.md
Labels: Microsoft submitter

#716 Publish main to live, Thursday 10:30 AM PST, 10/24
  sharepoint/sharepoint-ps/sharepoint-online/Copy-SPOPersonalSitePage.md
Labels: Microsoft submitter

#717 Change HidePeoplePresenceInLists to HidePeopleWhoHaveListsOpen
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOSite.md
Labels: In review, Microsoft submitter, Sign off

#719 publish main to live, 10/25/24, 3:30 pm
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOSite.md
Labels: Microsoft submitter

#718 Update Set-SPOTenant.md
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md
Labels: Microsoft submitter, Sign off

#720 publish main to live, 3:30 pm, 10/28/24
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md
Labels: Microsoft submitter

#722 Removing Preview Description for New-SPOListFileVersionBatchDeleteJob.md
  sharepoint/sharepoint-ps/sharepoint-online/New-SPOListFileVersionBatchDeleteJob.md
Labels: Sign off

#723 Publish main to live 10/31/2024, 3:30 PM
  sharepoint/sharepoint-ps/sharepoint-online/New-SPOListFileVersionBatchDeleteJob.md
Labels: Microsoft submitter
