Repository MicrosoftDocs/OfficeDocs-SharePoint-PowerShell, pull requests merged in 2024-05, with the labels that each got.

#624 Update BlockUserInfoVisibility doc
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md
Labels: In review, Microsoft submitter, Sign off

#625 Publish main to live 05/06/2024, 3:30 PM
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md
Labels: Microsoft submitter

#628 Update Set-SPOTenant.md
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md
Labels: In review, Microsoft submitter, Sign off

#634 Publish main to live 05/20/2024, 3:30 PM
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md
Labels: Microsoft submitter

#629 Create Set-SPOContainerTypeConfiguration
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOContainerTypeConfiguration
Labels: In review, Microsoft submitter, Sign off

#631 Create Set-SPOApplication
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOApplication
Labels: In review, Microsoft submitter, Sign off

#630 Create Get-SPOContainertypeConfiguration
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOContainerTypeConfiguration
Labels: In review, Microsoft submitter, Sign off

#635 Publish main to live, 05/21, 3:30 PM IST
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOContainerTypeConfiguration
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOApplication
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOContainerTypeConfiguration
Labels: Microsoft submitter

#627 Update Set-SPOTenant.md
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md
Labels: Microsoft submitter

#626 Update Set-SPOTenant.md
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md
Labels: Microsoft submitter

#632 Update Set-SPOSite.md
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOSite.md
Labels: Microsoft submitter

#636 Revert "Update Set-SPOSite.md"
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOSite.md
Labels: Microsoft submitter

#638 publish main to live 10:30 AM 5/22/24
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md
Labels: Microsoft submitter

#639 Publish main to live 05/24/2024, 3:30 PM
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOApplication.md
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOSite.md
Labels: Microsoft submitter

#640 update Set-SPOTenant
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md
Labels: In review, Sign off

#641 publish main to live 10:30 5/28/24
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md
Labels: Microsoft submitter
