Repository MicrosoftDocs/OfficeDocs-SharePoint-PowerShell, pull requests merged in 2024-04, with the labels that each got.

#615 Create ContentOwners.txt
  ContentOwners.txt
Labels: Microsoft submitter

#616 merging content owner changes to live
  ContentOwners.txt
Labels: Microsoft submitter

#572 Add IsDataAccessInCardDesignerEnabled flag
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md
Labels: Microsoft submitter

#618 publish main to live, 10:30 AM 4/10/24
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md
Labels: Microsoft submitter

#613 Create Get-SPOTenantRenameSitePrioritization.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOTenantRenameSitePrioritization.md
  sharepoint/sharepoint-ps/sharepoint-online/sharepoint-online.md
Labels: Back to submitter, In review, Microsoft submitter, Sign off

#582 Add details to Add-SPOListdesign to support rollout of doc lib org te…
  sharepoint/sharepoint-ps/sharepoint-online/Add-SPOListDesign.md
Labels: In review, Sign off

#619 Publish main to live, Wednesday 3:30PM PDT, 04/10
  sharepoint/sharepoint-ps/sharepoint-online/Add-SPOListDesign.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOTenantRenameSitePrioritization.md
  sharepoint/sharepoint-ps/sharepoint-online/Remove-SPOTenantRenameSitePrioritization.md
  sharepoint/sharepoint-ps/sharepoint-online/sharepoint-online.md
Labels: Microsoft submitter

#620 [FileVersion] Add and Update documentation
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOListFileVersionBatchDeleteJobProgress.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOListFileVersionExpirationReportJobProgress.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOListVersionPolicy.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOSiteFileVersionBatchDeleteJobProgress.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOSiteFileVersionExpirationReportJobProgress.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOSiteVersionPolicyJobProgress.md
  sharepoint/sharepoint-ps/sharepoint-online/New-SPOListFileVersionBatchDeleteJob.md
  sharepoint/sharepoint-ps/sharepoint-online/New-SPOListFileVersionExpirationReportJob.md
  sharepoint/sharepoint-ps/sharepoint-online/New-SPOSiteFileVersionBatchDeleteJob.md
  sharepoint/sharepoint-ps/sharepoint-online/New-SPOSiteFileVersionExpirationReportJob.md
  sharepoint/sharepoint-ps/sharepoint-online/Remove-SPOListFileVersionBatchDeleteJob.md
  sharepoint/sharepoint-ps/sharepoint-online/Remove-SPOSiteFileVersionBatchDeleteJob.md
  sharepoint/sharepoint-ps/sharepoint-online/Remove-SPOSiteVersionPolicyJob.md
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOListVersionPolicy.md
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOSite.md
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md
  sharepoint/sharepoint-ps/sharepoint-online/sharepoint-online.md
Labels: In review, Microsoft submitter, Sign off

#622 Publish main to live 04/29/2024, 3:30 PM
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOListFileVersionBatchDeleteJobProgress.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOListFileVersionExpirationReportJobProgress.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOListVersionPolicy.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOSiteFileVersionBatchDeleteJobProgress.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOSiteFileVersionExpirationReportJobProgress.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOSiteVersionPolicyJobProgress.md
  sharepoint/sharepoint-ps/sharepoint-online/New-SPOListFileVersionBatchDeleteJob.md
  sharepoint/sharepoint-ps/sharepoint-online/New-SPOListFileVersionExpirationReportJob.md
  sharepoint/sharepoint-ps/sharepoint-online/New-SPOSiteFileVersionBatchDeleteJob.md
  sharepoint/sharepoint-ps/sharepoint-online/New-SPOSiteFileVersionExpirationReportJob.md
  sharepoint/sharepoint-ps/sharepoint-online/Remove-SPOListFileVersionBatchDeleteJob.md
  sharepoint/sharepoint-ps/sharepoint-online/Remove-SPOSiteFileVersionBatchDeleteJob.md
  sharepoint/sharepoint-ps/sharepoint-online/Remove-SPOSiteVersionPolicyJob.md
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOListVersionPolicy.md
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOSite.md
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md
  sharepoint/sharepoint-ps/sharepoint-online/sharepoint-online.md
Labels: Microsoft submitter

#621 remove ShowOpenInDesktopOptionForSyncedFiles from documentation
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md
Labels: In review, Microsoft submitter, Sign off

#623 publish main to live 10:30 AM 4/30/24
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md
Labels: Microsoft submitter
