Repository MicrosoftDocs/OfficeDocs-SharePoint-PowerShell, pull requests merged in 2024-11, with the labels that each got.

#724 Remove Public preview tag for EnableAutoExpirationVersionTrim
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md
Labels: In review, Sign off

#725 Publish main to live, Tuesday 6:30PM PST, 11/5
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md
Labels: Microsoft submitter

#726 Correct localization metadata
  sharepoint/docs-conceptual/index.yml
  sharepoint/docs-conceptual/sharepoint-online/index.yml
  sharepoint/docs-conceptual/sharepoint-pnp/index.yml
  sharepoint/docs-conceptual/sharepoint-server/index.yml
Labels: Microsoft submitter, sharepoint-online/svc, subservice/subsvc

#728 Update New-SPOSiteFileVersionExpirationReportJob
  sharepoint/sharepoint-ps/sharepoint-online/New-SPOSiteFileVersionExpirationReportJob.md
Labels: In review, Sign off

#731 Update New-SPOSiteFileVersionBatchDeleteJob.md
  sharepoint/sharepoint-ps/sharepoint-online/New-SPOSiteFileVersionBatchDeleteJob.md
Labels: In review, Sign off

#732 Update Get-SPOListFileVersionBatchDeleteJobProgress.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOListFileVersionBatchDeleteJobProgress.md
Labels: In review, Sign off

#733 Update Get-SPOListFileVersionExpirationReportJobProgress.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOListFileVersionExpirationReportJobProgress.md
Labels: In review, Sign off

#734 Update Get-SPOListVersionPolicy.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOListVersionPolicy.md
Labels: In review, Sign off

#735 Update Remove-SPOListFileVersionBatchDeleteJob.md
  sharepoint/sharepoint-ps/sharepoint-online/Remove-SPOListFileVersionBatchDeleteJob.md
Labels: In review, Sign off

#736 Update Remove-SPOSiteFileVersionBatchDeleteJob.md
  sharepoint/sharepoint-ps/sharepoint-online/Remove-SPOSiteFileVersionBatchDeleteJob.md
Labels: In review, Sign off

#737 Publish main to live, Thursday 3:30PM PST, 11/07
  sharepoint/docs-conceptual/index.yml
  sharepoint/docs-conceptual/sharepoint-online/index.yml
  sharepoint/docs-conceptual/sharepoint-pnp/index.yml
  sharepoint/docs-conceptual/sharepoint-server/index.yml
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOListFileVersionBatchDeleteJobProgress.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOListFileVersionExpirationReportJobProgress.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOListVersionPolicy.md
  sharepoint/sharepoint-ps/sharepoint-online/New-SPOListFileVersionExpirationReportJob.md
  sharepoint/sharepoint-ps/sharepoint-online/New-SPOSiteFileVersionBatchDeleteJob.md
  sharepoint/sharepoint-ps/sharepoint-online/New-SPOSiteFileVersionExpirationReportJob.md
  sharepoint/sharepoint-ps/sharepoint-online/Remove-SPOListFileVersionBatchDeleteJob.md
  sharepoint/sharepoint-ps/sharepoint-online/Remove-SPOSiteFileVersionBatchDeleteJob.md
Labels: Microsoft submitter, sharepoint-online/svc, subservice/subsvc

#730 Update Get-SPOSiteFileVersionExpirationReportJobProgress.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOSiteFileVersionExpirationReportJobProgress.md
Labels: In review, Sign off

#739 Publish main to live, 11/08, 11:00 AM IST
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOSiteFileVersionExpirationReportJobProgress.md
Labels: Microsoft submitter

#738 Update Set-SPOListVersionPolicy.md
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOListVersionPolicy.md
Labels: In review, Sign off

#671 Container type cmdlets PR
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOContainerType.md
  sharepoint/sharepoint-ps/sharepoint-online/New-SPOContainerType.md
  sharepoint/sharepoint-ps/sharepoint-online/Remove-SPOContainerType.md
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOContainerType.md
Labels: In review, Sign off

#740 Publish main to live, Friday 5:00 PM IST, 11/08
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOContainerType.md
  sharepoint/sharepoint-ps/sharepoint-online/New-SPOContainerType.md
  sharepoint/sharepoint-ps/sharepoint-online/Remove-SPOContainerType.md
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOContainerType.md
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOListVersionPolicy.md
Labels: Microsoft submitter

#744 Update Remove-SPOSiteVersionPolicyJob.md
  sharepoint/sharepoint-ps/sharepoint-online/Remove-SPOSiteVersionPolicyJob.md
Labels: In review, Sign off

#743 Update Get-SPOSiteVersionPolicyJobProgress.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOSiteVersionPolicyJobProgress.md
Labels: In review, Sign off

#742 Update Get-SPOSiteFileVersionBatchDeleteJobProgress.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOSiteFileVersionBatchDeleteJobProgress.md
Labels: In review, Sign off

#747 Publish main to live 10/08/2024, 3:30 PM
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOSiteFileVersionBatchDeleteJobProgress.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOSiteVersionPolicyJobProgress.md
  sharepoint/sharepoint-ps/sharepoint-online/Remove-SPOSiteVersionPolicyJob.md
Labels: Microsoft submitter

#750 Adding 6 new commands for SPO data access gov
  sharepoint/sharepoint-ps/sharepoint-online/Export-SPODataAccessGovernanceInsight.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPODataAccessGovernanceInsight.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOSiteReview.md
  sharepoint/sharepoint-ps/sharepoint-online/Remove-SPODataAccessGovernanceInsight.md
  sharepoint/sharepoint-ps/sharepoint-online/Start-SPODataAccessGovernanceInsight.md
  sharepoint/sharepoint-ps/sharepoint-online/Start-SPOSiteReview.md
Labels: In review, Microsoft submitter, Sign off

#751 Publish main to live, Monday 5:00 PM IST, 11/11
  sharepoint/sharepoint-ps/sharepoint-online/Export-SPODataAccessGovernanceInsight.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPODataAccessGovernanceInsight.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOSiteReview.md
  sharepoint/sharepoint-ps/sharepoint-online/Remove-SPODataAccessGovernanceInsight.md
  sharepoint/sharepoint-ps/sharepoint-online/Start-SPODataAccessGovernanceInsight.md
  sharepoint/sharepoint-ps/sharepoint-online/Start-SPOSiteReview.md
Labels: Microsoft submitter

#752 Revert "Adding 6 new commands for SPO data access gov"
  sharepoint/sharepoint-ps/sharepoint-online/Export-SPODataAccessGovernanceInsight.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPODataAccessGovernanceInsight.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOSiteReview.md
  sharepoint/sharepoint-ps/sharepoint-online/Remove-SPODataAccessGovernanceInsight.md
  sharepoint/sharepoint-ps/sharepoint-online/Start-SPODataAccessGovernanceInsight.md
  sharepoint/sharepoint-ps/sharepoint-online/Start-SPOSiteReview.md
Labels: Microsoft submitter, Sign off

#741 Update Set-SPOSite.md
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOSite.md
Labels: In review, Microsoft submitter, Sign off

#745 SPOCopilotPromoOptInStatus.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOCopilotPromoOptInStatus.md
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOCopilotPromoOptInStatus.md
Labels: In review, Sign off

#715 SPORestrictedAccessForSitesInsights cmdlet documentation
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPORestrictedAccessForSitesInsights.md
  sharepoint/sharepoint-ps/sharepoint-online/Start-SPORestrictedAccessForSitesInsights.md
Labels: In review, Microsoft submitter, Sign off

#754 Update redirection for removed files
  .openpublishing.redirection.json
Labels: In review, Microsoft submitter

#753 Publish main to live, 11/12, 11:00 AM IST
  .openpublishing.redirection.json
  sharepoint/sharepoint-ps/sharepoint-online/Export-SPODataAccessGovernanceInsight.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOCopilotPromoOptInStatus.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPODataAccessGovernanceInsight.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPORestrictedAccessForSitesInsights.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOSiteReview.md
  sharepoint/sharepoint-ps/sharepoint-online/Remove-SPODataAccessGovernanceInsight.md
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOCopilotPromoOptInStatus.md
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOSite.md
  sharepoint/sharepoint-ps/sharepoint-online/Start-SPODataAccessGovernanceInsight.md
  sharepoint/sharepoint-ps/sharepoint-online/Start-SPORestrictedAccessForSitesInsights.md
  sharepoint/sharepoint-ps/sharepoint-online/Start-SPOSiteReview.md
Labels: Microsoft submitter

#756 New PS commands for DAG
  .openpublishing.redirection.json
  sharepoint/sharepoint-ps/sharepoint-online/Export-SPODataAccessGovernanceInsight.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPODataAccessGovernanceInsight.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOSiteReview.md
  sharepoint/sharepoint-ps/sharepoint-online/Remove-SPODataAccessGovernanceInsight.md
  sharepoint/sharepoint-ps/sharepoint-online/Start-SPODataAccessGovernanceInsight.md
  sharepoint/sharepoint-ps/sharepoint-online/Start-SPOSiteReview.md
Labels: In review, Microsoft submitter, Sign off

#763 Update Set-SPOCopilotPromoOptInStatus.md
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOCopilotPromoOptInStatus.md
Labels: In review, Sign off

#764 Publish main to live, Tuesday 3:30PM PST, 11/26
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOCopilotPromoOptInStatus.md
Labels: Microsoft submitter

#766 Update Get-SPOCopilotPromoOptInStatus.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOCopilotPromoOptInStatus.md
Labels: In review, Sign off
