Repository MicrosoftDocs/OfficeDocs-SharePoint-PowerShell, pull requests merged in 2024-09, with the labels that each got.

#679 Publish main to live, 09/02, 11:00 AM IST
  sharepoint/sharepoint-ps/sharepoint-online/Get-FileSensitivityLabelInfo.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOAppErrors.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOAppInfo.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOContainer.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOCrossGeoMovedUsers.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOCrossGeoUsers.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOCrossTenantCompatibilityStatus.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOCrossTenantHostUrl.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPODeletedContainer.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPODeletedSite.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOGeoAdministrator.md
Labels: Microsoft submitter

#673 Add public documentation for page move IT-facing solution
  sharepoint/sharepoint-ps/sharepoint-online/Copy-SPOPersonalSitePage.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOPersonalSitePageCopyProgress.md
Labels: Microsoft submitter

#680 publish main to live 9/3 10:30 AM
  sharepoint/sharepoint-ps/sharepoint-online/Copy-SPOPersonalSitePage.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOPersonalSitePageCopyProgress.md
Labels: Microsoft submitter

#670 Adds documentation to Set-SPOTenant.md detailing the new parameters added for supporting Syntex model features' tenant settings
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md
Labels: In review, Microsoft submitter, Sign off

#681 Global admin security updates
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOGeoStorageQuota.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOMalwareFile.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOMalwareFileContent.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOSite.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOTenant.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOTenantCdnOrigins.md
Labels: In review, Microsoft submitter, Sign off

#683 2nd batch of sharepoint powershell global admin mentioning removal
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOSiteGroup.md
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOSiteOffice365Group.md
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenantRenameSitePrioritization.md
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenantSyncClientRestriction.md
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOUser.md
  sharepoint/sharepoint-ps/sharepoint-online/Start-SPOUserAndContentMove.md
  sharepoint/sharepoint-ps/sharepoint-online/Test-SPOSite.md
  sharepoint/sharepoint-ps/sharepoint-online/Unlock-SPOSensitivityLabelEncryptedFile.md
  sharepoint/sharepoint-ps/sharepoint-online/Upgrade-SPOSite.md
Labels: In review, Microsoft submitter, Sign off

#682 update powershell articles mentioning glob admin
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOTenantLogEntry.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOTenantLogLastAvailableTimeInUtc.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOTenantRenameSitePrioritization.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOTenantSyncClientRestriction.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOUser.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOWebTemplate.md
  sharepoint/sharepoint-ps/sharepoint-online/New-SPOSite.md
  sharepoint/sharepoint-ps/sharepoint-online/New-SPOSiteGroup.md
  sharepoint/sharepoint-ps/sharepoint-online/Remove-SPOContainer.md
  sharepoint/sharepoint-ps/sharepoint-online/Remove-SPODeletedContainer.md
  sharepoint/sharepoint-ps/sharepoint-online/Remove-SPODeletedSite.md
  sharepoint/sharepoint-ps/sharepoint-online/Remove-SPOGeoAdministrator.md
  sharepoint/sharepoint-ps/sharepoint-online/Remove-SPOSite.md
  sharepoint/sharepoint-ps/sharepoint-online/Remove-SPOSiteGroup.md
  sharepoint/sharepoint-ps/sharepoint-online/Remove-SPOTenantRenameSitePrioritization.md
  sharepoint/sharepoint-ps/sharepoint-online/Remove-SPOTenantSyncClientRestriction.md
  sharepoint/sharepoint-ps/sharepoint-online/Remove-SPOUser.md
  sharepoint/sharepoint-ps/sharepoint-online/Repair-SPOSite.md
  sharepoint/sharepoint-ps/sharepoint-online/Request-SPOUpgradeEvaluationSite.md
  sharepoint/sharepoint-ps/sharepoint-online/Restore-SPODeletedContainer.md
  sharepoint/sharepoint-ps/sharepoint-online/Restore-SPODeletedSite.md
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOContainer.md
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOGeoStorageQuota.md
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOOrgNewsSite.md
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOSiteArchiveState.md
Labels: In review, Microsoft submitter, Sign off

#684 Publish main to live, Tuesday 3:30PM PDT, 09/03
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOGeoStorageQuota.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOMalwareFile.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOMalwareFileContent.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOSite.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOTenant.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOTenantCdnOrigins.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOTenantLogEntry.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOTenantLogLastAvailableTimeInUtc.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOTenantRenameSitePrioritization.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOTenantSyncClientRestriction.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOUser.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOWebTemplate.md
  sharepoint/sharepoint-ps/sharepoint-online/New-SPOSite.md
  sharepoint/sharepoint-ps/sharepoint-online/New-SPOSiteGroup.md
  sharepoint/sharepoint-ps/sharepoint-online/Remove-SPOContainer.md
  sharepoint/sharepoint-ps/sharepoint-online/Remove-SPODeletedContainer.md
  sharepoint/sharepoint-ps/sharepoint-online/Remove-SPODeletedSite.md
  sharepoint/sharepoint-ps/sharepoint-online/Remove-SPOGeoAdministrator.md
  sharepoint/sharepoint-ps/sharepoint-online/Remove-SPOSite.md
  sharepoint/sharepoint-ps/sharepoint-online/Remove-SPOSiteGroup.md
  sharepoint/sharepoint-ps/sharepoint-online/Remove-SPOTenantRenameSitePrioritization.md
  sharepoint/sharepoint-ps/sharepoint-online/Remove-SPOTenantSyncClientRestriction.md
  sharepoint/sharepoint-ps/sharepoint-online/Remove-SPOUser.md
  sharepoint/sharepoint-ps/sharepoint-online/Repair-SPOSite.md
  sharepoint/sharepoint-ps/sharepoint-online/Request-SPOUpgradeEvaluationSite.md
  sharepoint/sharepoint-ps/sharepoint-online/Restore-SPODeletedContainer.md
  sharepoint/sharepoint-ps/sharepoint-online/Restore-SPODeletedSite.md
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOContainer.md
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOGeoStorageQuota.md
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOOrgNewsSite.md
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOSiteArchiveState.md
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOSiteGroup.md
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOSiteOffice365Group.md
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenantRenameSitePrioritization.md
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenantSyncClientRestriction.md
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOUser.md
  sharepoint/sharepoint-ps/sharepoint-online/Start-SPOUserAndContentMove.md
  sharepoint/sharepoint-ps/sharepoint-online/Test-SPOSite.md
  sharepoint/sharepoint-ps/sharepoint-online/Unlock-SPOSensitivityLabelEncryptedFile.md
  sharepoint/sharepoint-ps/sharepoint-online/Upgrade-SPOSite.md
Labels: Microsoft submitter

#686 publish main to live 10:30 AM 9/5/2024
  sharepoint/sharepoint-ps/sharepoint-online/Copy-SPOPersonalSitePage.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOPersonalSitePageCopyProgress.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOSitePages.md
Labels: Microsoft submitter

#687 Update SPOContentSecurityPolicy cmdlets
  sharepoint/sharepoint-ps/sharepoint-online/Add-SPOContentSecurityPolicy.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOContentSecurityPolicy.md
  sharepoint/sharepoint-ps/sharepoint-online/Remove-SPOContentSecurityPolicy.md
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md
Labels: Microsoft submitter

#690 Publish main to live, Tuesday 3:30PM PDT, 09/10
  sharepoint/sharepoint-ps/sharepoint-online/Add-SPOContentSecurityPolicy.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOContentSecurityPolicy.md
  sharepoint/sharepoint-ps/sharepoint-online/Remove-SPOContentSecurityPolicy.md
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md
Labels: Microsoft submitter

#689 Update Set-SPOTenant.md
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md
Labels: In review, Sign off

#693 Publish main to live 09/16/2024, 3:30 PM
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md
Labels: Microsoft submitter

#691 Updates Set-SPOTenant.md to include documentation for new parameters which add support for the remaining Syntex features
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md
Labels: Microsoft submitter

#695 Publish main to live, Tuesday 3:30PM PDT, 09/24
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md
Labels: Microsoft submitter

#697 Publish main to live, Wednesday 3:30PM PDT, 09/25
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOEnterpriseAppInsightsReport.md
  sharepoint/sharepoint-ps/sharepoint-online/Start-SPOEnterpriseAppInsightsReport.md
Labels: Microsoft submitter

#688 Add HidePeoplePreviewingFiles
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOSite.md
Labels: In review, Microsoft submitter, Sign off

#699 Publish main to live, Thursday 3:30PM PDT, 09/26
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOSite.md
Labels: Microsoft submitter

#698 Add WhoCanShare AllowLists to SetSPOTenant.md
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md
Labels: Microsoft submitter

#700 Publish main to live, Friday 3:30PM PDT, 09/27
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md
Labels: Microsoft submitter
