Repository MicrosoftDocs/OfficeDocs-SharePoint-PowerShell, pull requests merged in 2024-03, with the labels that each got.

#590 Add default value for ms.topic: reference
  sharepoint/docfx.json
Labels: Microsoft submitter

#591 merge main to live 3:30 PM 3/14/24
  sharepoint/docfx.json
Labels: Microsoft submitter

#589 Create Set-SPOTenantRenameSitePrioritization.md
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenantRenameSitePrioritization.md
Labels: In review, Microsoft submitter, Sign off

#592 Publish main to live, 03/19, 3:30 PM IST
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenantRenameSitePrioritization.md
Labels: Microsoft submitter

#587 Update Set-SPOTenant.md
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md
Labels: Microsoft submitter

#596 Publish main to live, Wednesday 10:30AM PDT, 03/20
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md
Labels: Microsoft submitter

#595 Update Set-SPOTenantRenameSitePrioritization.md - link fix from publi…
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenantRenameSitePrioritization.md
Labels: Admin review, Microsoft submitter

#597 Publish main to live, 03/21, 3:30 PM IST
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenantRenameSitePrioritization.md
Labels: Microsoft submitter

#579 Add sharepointaddinsdisabled cmdlet
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md
Labels: In review, Microsoft submitter, Sign off

#599 Update date for DelayDenyAddAndCustomizePagesEnforcement command
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md
Labels: Microsoft submitter

#601 publish main to live 10:30 AM 3/25/24
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md
Labels: Microsoft submitter

#588 tws cmdlets documentation
  sharepoint/sharepoint-ps/sharepoint-online/Add-SPOTenantRestrictedSearchAllowedList.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOTenantRestrictedSearchAllowedList.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOTenantRestrictedSearchMode.md
  sharepoint/sharepoint-ps/sharepoint-online/Remove-SPOTenantRestrictedSearchAllowedList.md
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenantRestrictedSearchMode.md
Labels: Microsoft submitter

#603 Correct "author": replace "praporwal" with "praporwal-microsoft"
  sharepoint/sharepoint-ps/sharepoint-online/Add-SPOTenantRestrictedSearchAllowedList.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOTenantRestrictedSearchAllowedList.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOTenantRestrictedSearchMode.md
  sharepoint/sharepoint-ps/sharepoint-online/Remove-SPOTenantRestrictedSearchAllowedList.md
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenantRestrictedSearchMode.md
Labels: Microsoft submitter

#602 Publish main to live, Tuesday 3:30PM PDT, 03/26
  sharepoint/sharepoint-ps/sharepoint-online/Add-SPOTenantRestrictedSearchAllowedList.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOTenantRestrictedSearchAllowedList.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOTenantRestrictedSearchMode.md
  sharepoint/sharepoint-ps/sharepoint-online/Remove-SPOTenantRestrictedSearchAllowedList.md
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenantRestrictedSearchMode.md
Labels: Microsoft submitter

#605 Fix redirection
  .openpublishing.publish.config.json
  .openpublishing.redirection.json
Labels: Microsoft submitter

#606 Remove protocol and domain to create site-relative links
  .openpublishing.redirection.json
Labels: Microsoft submitter

#608 publish main to live 3:30 pm 3/28/24
  .openpublishing.publish.config.json
  .openpublishing.redirection.json
Labels: Microsoft submitter

#609 Add virtual folder entries
  sharepoint/docfx.json
Labels: Microsoft submitter

#611 Publish main to live, Friday 10:30AM PDT, 03/29
  sharepoint/docfx.json
Labels: Microsoft submitter

#604 revert tws cmdlet documentation
  .openpublishing.redirection.json
  sharepoint/sharepoint-ps/sharepoint-online/Add-SPOTenantRestrictedSearchAllowedList.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOTenantRestrictedSearchAllowedList.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOTenantRestrictedSearchMode.md
  sharepoint/sharepoint-ps/sharepoint-online/Remove-SPOTenantRestrictedSearchAllowedList.md
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenantRestrictedSearchMode.md
Labels: Back to submitter

#612 Publish main to live 03/29/2024, 3:30 PM
  .openpublishing.redirection.json
  sharepoint/sharepoint-ps/sharepoint-online/Add-SPOTenantRestrictedSearchAllowedList.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOTenantRestrictedSearchAllowedList.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOTenantRestrictedSearchMode.md
  sharepoint/sharepoint-ps/sharepoint-online/Remove-SPOTenantRestrictedSearchAllowedList.md
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenantRestrictedSearchMode.md
Labels: Microsoft submitter
