Repository MicrosoftDocs/OfficeDocs-SharePoint-PowerShell, pull requests merged in 2025-04, with the labels that each got.

#851 Update New-SPConfigurationDatabase.md
  sharepoint/sharepoint-server-ps/sharepoint-server/New-SPConfigurationDatabase.md
Labels: In review, Microsoft submitter, Sign off

#855 Published main to live, Wednesday 10:30 AM PST, 04/02
  sharepoint/sharepoint-server-ps/sharepoint-server/New-SPConfigurationDatabase.md
Labels: Microsoft submitter

#843 Update Connect-SPConfigurationDatabase.md
  sharepoint/sharepoint-server-ps/sharepoint-server/Connect-SPConfigurationDatabase.md
Labels: In review, Microsoft submitter, Sign off

#856 Publish main to live, 04/02/25, 3:30 PM PDT
  sharepoint/sharepoint-server-ps/sharepoint-server/Connect-SPConfigurationDatabase.md
Labels: Microsoft submitter

#858 Merge AutoPublish workflow to live
  .github/workflows/AutoPublish.yml
Labels: Microsoft submitter

#861 Documentation for Opt-in
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOAuditDataCollectionStatusForActivityInsights.md
  sharepoint/sharepoint-ps/sharepoint-online/Start-SPOAuditDataCollectionForActivityInsights.md
  sharepoint/sharepoint-ps/sharepoint-online/Stop-SPOAuditDataCollectionForActivityInsights.md
  sharepoint/sharepoint-ps/sharepoint-online/sharepoint-online.md
Labels: In review, Microsoft submitter, Sign off

#860 Update Set-SPOTenant.md
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md
Labels: In review, Microsoft submitter, Sign off

#862 Update Get-SPOCrossTenantCompatibilityStatus.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOCrossTenantCompatibilityStatus.md
Labels: In review, Microsoft submitter, Sign off

#869 StaleBranch reporting updates and cron changes to live
  .github/workflows/StaleBranch.yml
Labels: Microsoft submitter

#867 Update New-SPOContainerType.md
  sharepoint/sharepoint-ps/sharepoint-online/New-SPOContainerType.md
Labels: In review, Microsoft submitter, Sign off

#865 Update Set-SPOSite.md
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOSite.md
Labels: In review, Microsoft submitter, Sign off

#871 Update Set-SPOTenant.md
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md
Labels: In review, Microsoft submitter, Sign off

#874 Update Get-SPOCopilotPromoUsage.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOCopilotPromoUsage.md
Labels: In review, Microsoft submitter, Sign off

#876 Update Set-SPOSite.md: Update supported parameters for group sites
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOSite.md
Labels: In review, Microsoft submitter, Sign off

#879 Addressing build issues and quality problems in sharepoint-online documentation
  sharepoint/docs-conceptual/sharepoint-online/connect-sharepoint-online.md
  sharepoint/docs-conceptual/sharepoint-online/introduction-sharepoint-online-management-shell.md
  sharepoint/sharepoint-ps/sharepoint-online/Invoke-SPOSiteSwap.md
  sharepoint/sharepoint-ps/sharepoint-online/New-SPOMigrationPackage.md
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md
Labels: In review, Microsoft submitter, Sign off, PubOps fixes
