Repository MicrosoftDocs/OfficeDocs-SharePoint-PowerShell, pull requests merged in 2025-03, with the labels that each got.

#820 Publish main to live, 03/03, 11:00 AM IST
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md
Labels: Microsoft submitter

#812 Add Documentation for SPOTenantPreAuthSettings
  sharepoint/sharepoint-ps/sharepoint-online/Clear-SPOTenantPreAuthSettings.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOTenantPreAuthSettings.md
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenantPreAuthSettings.md
  sharepoint/sharepoint-ps/sharepoint-online/sharepoint-online.md
Labels: In review, Microsoft submitter, Sign off

#822 Publish main to live, 03/03/25, 3:30 PM PT
  sharepoint/sharepoint-ps/sharepoint-online/Clear-SPOTenantPreAuthSettings.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOTenantPreAuthSettings.md
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenantPreAuthSettings.md
  sharepoint/sharepoint-ps/sharepoint-online/sharepoint-online.md
Labels: Microsoft submitter

#821 Add WhoCanShare Settings to Set-SPOContainerTypeConfiguration
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOContainerTypeConfiguration.md
Labels: In review, Microsoft submitter, Sign off

#824 Publish main to live 03/04/2025, 10:30 AM (late)
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOContainerTypeConfiguration.md
Labels: Microsoft submitter

#823 Made fixes to include table of feature names + improve formatting
  sharepoint/sharepoint-ps/sharepoint-online/Clear-SPOTenantPreAuthSettings.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOTenantPreAuthSettings.md
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenantPreAuthSettings.md
Labels: In review, Microsoft submitter, Sign off

#826 Publish main to live, 03/05, 11:00 AM IST
  sharepoint/sharepoint-ps/sharepoint-online/Clear-SPOTenantPreAuthSettings.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOTenantPreAuthSettings.md
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenantPreAuthSettings.md
Labels: Microsoft submitter

#825 Update Set-SPOTenant.md to add EnforceRequestDigest setting
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md
Labels: In review, Microsoft submitter, Sign off

#828 Publish main to live, 03/06, 11:00 AM IST
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md
Labels: Microsoft submitter

#829 Update AutoLabelMsftContributor workflow from PAT to GH app
  .github/workflows/AutoLabelMsftContributor.yml
Labels: Microsoft submitter

#831 Publish main to live, 03/11, 11:00 AM IST
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md
Labels: Microsoft submitter

#827 Archived containers modification.
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOContainer.md
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOContainer.md
Labels: In review, Microsoft submitter, Sign off

#832 Add a new command named DisableSharePointStoreAccess
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md
Labels: In review, Microsoft submitter, Sign off

#834 Publish main to live, 03/13/25, 10:30 AM PDT
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md
Labels: Microsoft submitter

#835 Fix article syntax
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOCopilotPromoOptInStatus.md
Labels: Microsoft submitter

#836 Fix article syntax
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOCopilotPromoOptInStatus.md
Labels: Microsoft submitter

#837 update workflows
  .github/workflows/AutoLabelAssign.yml
  .github/workflows/AutoLabelMsftContributor.yml
  .github/workflows/BuildValidation.yml
  .github/workflows/LiveMergeCheck.yml
  .github/workflows/PrFileCount.yml
  .github/workflows/ProtectedFiles.yml
  .github/workflows/Stale.yml
  .github/workflows/StaleBranch.yml
  .github/workflows/TierManagement.yml
Labels: Microsoft submitter

#839 Create Start-SPOSiteOpticalCharacterRecognitionBackfill.md
  sharepoint/sharepoint-ps/sharepoint-online/Start-SPOSiteOpticalCharacterRecognitionBackfill.md
  sharepoint/sharepoint-ps/sharepoint-online/sharepoint-online.md
Labels: Microsoft submitter, Sign off

#841 Publish main to live, 03/19/25, 3:30 PM PDT
  sharepoint/sharepoint-ps/sharepoint-online/Start-SPOSiteOpticalCharacterRecognitionBackfill.md
  sharepoint/sharepoint-ps/sharepoint-online/sharepoint-online.md
Labels: Microsoft submitter

#840 Added SPO app priotization policy
  sharepoint/sharepoint-ps/sharepoint-online/Add-SPOAppPrioritizationPolicy.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOAppPrioritizationPolicies.md
  sharepoint/sharepoint-ps/sharepoint-online/Remove-SPOAppPrioritizationPolicy.md
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOAppPrioritizationPolicy.md
  sharepoint/sharepoint-ps/sharepoint-online/sharepoint-online.md
Labels: In review, Microsoft submitter, Sign off

#845 added note about still rolling out
  sharepoint/sharepoint-ps/sharepoint-online/Add-SPOAppPrioritizationPolicy.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOAppPrioritizationPolicies.md
  sharepoint/sharepoint-ps/sharepoint-online/Remove-SPOAppPrioritizationPolicy.md
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOAppPrioritizationPolicy.md
Labels: In review, Microsoft submitter, Sign off, PubOps fixes

#846 fixed information about Quota multiplier
  sharepoint/sharepoint-ps/sharepoint-online/Add-SPOAppPrioritizationPolicy.md
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOAppPrioritizationPolicy.md
Labels: In review, Microsoft submitter, Sign off

#848 Publish main to live, 03/26/25, 3:30 PM PDT
  .github/workflows/AutoLabelAssign.yml
  .github/workflows/AutoLabelMsftContributor.yml
  .github/workflows/BackgroundTasks.yml
  .github/workflows/BuildValidation.yml
  .github/workflows/LiveMergeCheck.yml
  .github/workflows/PrFileCount.yml
  .github/workflows/ProtectedFiles.yml
  .github/workflows/Stale.yml
  .github/workflows/StaleBranch.yml
  .github/workflows/TierManagement.yml
  sharepoint/sharepoint-ps/sharepoint-online/Add-SPOAppPrioritizationPolicy.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOAppPrioritizationPolicies.md
  sharepoint/sharepoint-ps/sharepoint-online/Remove-SPOAppPrioritizationPolicy.md
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOAppPrioritizationPolicy.md
Labels: Microsoft submitter

#838 add AllowFileArchive to Set-SPOSite
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOSite.md
Labels: In review, Microsoft submitter, Sign off, PubOps fixes

#849 Publish main to live, 03/28/25, 3:30 PM PDT
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOSite.md
Labels: Microsoft submitter

#853 Schedule to 1st of the month at 9am UTC. Disable manual trigger. Disa…
  .github/workflows/StaleBranch.yml
Labels: Microsoft submitter
