Repository MicrosoftDocs/OfficeDocs-SharePoint-PowerShell, pull requests merged in 2025-05, with the labels that each got.

#884 RCD for agents via PowerShell - preview
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOSite.md
Labels: In review, Microsoft submitter, Sign off

#888 Update Set-SPOApplication.md
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOApplication.md
Labels: In review, Sign off

#883 Changes as part of Copilot Embedded Chat host changes
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOContainerTypeConfiguration.md
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOApplication.md
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOContainerTypeConfiguration.md
Labels: In review, Microsoft submitter, Sign off

#882 Changes to Set-SPOContainerType cmdlet
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOContainerType.md
Labels: In review, Microsoft submitter, Sign off

#890 Updating proper syntax for RACInsights
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPORestrictedAccessForSitesInsights.md
Labels: In review, Microsoft submitter, Sign off

#859 Service Prioritization Name change from App prioritization
  .openpublishing.redirection.json
  sharepoint/sharepoint-ps/sharepoint-online/Add-SPOAppPrioritizationPolicy.md
  sharepoint/sharepoint-ps/sharepoint-online/Add-SPOServicePrioritizationAppRegistration.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOAppPrioritizationPolicies.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOServicePrioritizationAppRegistrations.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOServicePrioritizationBillingPolicies.md
  sharepoint/sharepoint-ps/sharepoint-online/New-SPOServicePrioritizationBillingPolicy.md
  sharepoint/sharepoint-ps/sharepoint-online/Remove-SPOAppPrioritizationPolicy.md
  sharepoint/sharepoint-ps/sharepoint-online/Remove-SPOServicePrioritizationAppRegistration.md
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOAppPrioritizationPolicy.md
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOServicePrioritizationAppRegistration.md
  sharepoint/sharepoint-ps/sharepoint-online/sharepoint-online.md
Labels: Microsoft submitter
