Repository MicrosoftDocs/OfficeDocs-SharePoint-PowerShell, pull requests merged in 2025-06, with the labels that each got.

#906 Update Set-SPOTenant.md
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md
Labels: Microsoft submitter

#905 AllowClassicPublishingSiteCreation - New parameter in Set-SPOTenant
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md
Labels: In review, Microsoft submitter, Sign off

#909 Revert "AllowClassicPublishingSiteCreation - New parameter in Set-SPOTenant"
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md
Labels: Microsoft submitter

#910 Revert "AllowClassicPublishingSiteCreation - New parameter in Set-SPOTenant"
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md
Labels: Microsoft submitter

#911 Update Set-SPOTenant.md with AllowClassicPublishingSiteCreation
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md
Labels: In review, Microsoft submitter, Sign off

#913 Documentation about 2 existing commands
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOInformationBarriersInsightsReport.md
  sharepoint/sharepoint-ps/sharepoint-online/Start-SPOInformationBarriersInsightsReport.md
Labels: In review, Microsoft submitter, Sign off, PubOps fixes, Triage-InProgress
