Repository MicrosoftDocs/OfficeDocs-SharePoint-PowerShell, pull requests merged in 2025-01, with the labels that each got.

#762 Update documentation of Set-SPOTenant and Set-SPOSite cmdlet
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOSite.md
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md
Labels: In review, Sign off

#783 Publish main to live, 01/03, 11:00 AM IST
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOSite.md
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md
Labels: Microsoft submitter

#784 Update Get-SPORestrictedAccessForSitesInsights.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPORestrictedAccessForSitesInsights.md
Labels: In review, Microsoft submitter, Sign off

#788 Publish main to live, 01/09/25, 3:30 PM PT
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPORestrictedAccessForSitesInsights.md
Labels: Microsoft submitter

#785 Sorting parameters alphabetically in Set-SPOSite.md
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOSite.md
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md
Labels: In review, Sign off

#790 Publish main to live 01/14/2024, 3:30 PM
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOSite.md
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md
Labels: Microsoft submitter

#789 Remove LocaleId from Set-SPOSite
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOSite.md
Labels: In review, Sign off

#791 Update Set-SPMachineKey.md
  sharepoint/sharepoint-server-ps/sharepoint-server/Set-SPMachineKey.md
Labels: In review, Microsoft submitter, Sign off

#793 Publish main to live, 01/23, 11:00 AM IST
  sharepoint/sharepoint-server-ps/sharepoint-server/Set-SPMachineKey.md
Labels: Microsoft submitter

#787 Update Get-SPORestrictedSiteCreation.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPORestrictedSiteCreation.md
Labels: In review, Microsoft submitter, Sign off

#794 Publish main to live, 01/27, 11:00 AM IST
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPORestrictedSiteCreation.md
Labels: Microsoft submitter

#795 Update Set-SPOTenant.md documentation
  sharepoint/docs-conceptual/index.yml
  sharepoint/docs-conceptual/sharepoint-online/index.yml
  sharepoint/docs-conceptual/sharepoint-pnp/index.yml
  sharepoint/docs-conceptual/sharepoint-server/index.yml
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md
Labels: In review, Sign off, sharepoint-online/svc

#796 Publish main to live, 01/28/25, 3:30 PM PT
  sharepoint/docs-conceptual/index.yml
  sharepoint/docs-conceptual/sharepoint-online/index.yml
  sharepoint/docs-conceptual/sharepoint-pnp/index.yml
  sharepoint/docs-conceptual/sharepoint-server/index.yml
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md
Labels: Microsoft submitter, sharepoint-online/svc
