Repository MicrosoftDocs/OfficeDocs-SharePoint-PowerShell, pull requests merged in 2025-02, with the labels that each got.

#755 New Container type lifecycle cmdlets
  sharepoint/sharepoint-ps/sharepoint-online/Add-SPOContainerTypeBilling.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOContainer.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOContainerType.md
  sharepoint/sharepoint-ps/sharepoint-online/New-SPOContainerType.md
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOContainerType.md
  sharepoint/sharepoint-ps/sharepoint-online/sharepoint-online.md
Labels: In review, Sign off

#799 Publish main to live, 02/04/25, 3:30 PM PT
  sharepoint/sharepoint-ps/sharepoint-online/Add-SPOContainerTypeBilling.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOContainer.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOContainerType.md
  sharepoint/sharepoint-ps/sharepoint-online/New-SPOContainerType.md
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOContainerType.md
  sharepoint/sharepoint-ps/sharepoint-online/sharepoint-online.md
Labels: Microsoft submitter

#797 Update Start-SPOCopilotAgentInsightsReport.md
  sharepoint/sharepoint-ps/sharepoint-online/Start-SPOCopilotAgentInsightsReport.md
Labels: In review, Microsoft submitter, Sign off

#798 Update Get-SPOCopilotAgentInsightsReport.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOCopilotAgentInsightsReport.md
Labels: In review, Microsoft submitter, Sign off

#800 Publish main to live, 02/05/25, 3:30 PM PT
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOCopilotAgentInsightsReport.md
  sharepoint/sharepoint-ps/sharepoint-online/Start-SPOCopilotAgentInsightsReport.md
Labels: Microsoft submitter

#802 Update README.md
  README.md
Labels: In review, Microsoft submitter, Sign off

#803 Published main to live, Thursday 10:30 AM PST, 02/06
  README.md
Labels: Microsoft submitter

#804 Add AllOrganizationSecurityGroupId to Set-SPOTenant.md
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md
Labels: Microsoft submitter

#806 Publish main to live, 02/07/25, 10:30 AM PT
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOTenant.md
Labels: Microsoft submitter

#805 Added Ruchika's alias
  sharepoint/docfx.json
Labels: In review, Microsoft submitter, Sign off

#807 Publish main to live, 02/07/25, 3:30 PM PT
  sharepoint/docfx.json
Labels: Microsoft submitter

#809 Update sharepoint-online.md
  sharepoint/sharepoint-ps/sharepoint-online/sharepoint-online.md
Labels: In review, Sign off

#810 Publish main to live, 02/11, 11:00 AM IST
  sharepoint/sharepoint-ps/sharepoint-online/sharepoint-online.md
Labels: Microsoft submitter

#808 Create Get-SPOCopilotPromoUsage
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOCopilotPromoUsage.md
Labels: In review, Sign off, PubOps fixes

#811 Publish main to live, 02/11/25, 3:30 PM PT
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOCopilotPromoUsage.md
Labels: Microsoft submitter

#815 Publish main to live, 02/24/25, 3:30 PM PT
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOApplication.md
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOApplication.md
Labels: Microsoft submitter

#659 Add commands for managing built-in font packages
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOBuiltInFontPackageSettings.md
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOBuiltInFontPackageSettings.md
  sharepoint/sharepoint-ps/sharepoint-online/sharepoint-online.md
Labels: In review, Microsoft submitter, Sign off

#816 Update Update-SPProfileSync.md
  sharepoint/sharepoint-server-ps/sharepoint-server/Update-SPProfileSync.md
Labels: In review, Sign off

#786 Documentation for the new private preview feature
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPODataAccessGovernanceInsight.md
  sharepoint/sharepoint-ps/sharepoint-online/Start-SPODataAccessGovernanceInsight.md
Labels: In review, Microsoft submitter, Sign off

#817 Published main to live, Tuesday 5:00 PM IST, 02/25
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPOBuiltInFontPackageSettings.md
  sharepoint/sharepoint-ps/sharepoint-online/Get-SPODataAccessGovernanceInsight.md
  sharepoint/sharepoint-ps/sharepoint-online/Set-SPOBuiltInFontPackageSettings.md
  sharepoint/sharepoint-ps/sharepoint-online/Start-SPODataAccessGovernanceInsight.md
  sharepoint/sharepoint-ps/sharepoint-online/sharepoint-online.md
  sharepoint/sharepoint-server-ps/sharepoint-server/Update-SPProfileSync.md
Labels: Microsoft submitter

#813 Update New-SPOContainerType.md
  sharepoint/sharepoint-ps/sharepoint-online/New-SPOContainerType.md
Labels: Admin review, In review, Microsoft submitter

#818 publish main to live, 2/25/25, 3:30 pm
  sharepoint/sharepoint-ps/sharepoint-online/New-SPOContainerType.md
Labels: Microsoft submitter
